### ISSUE TITLE
Unable to deploy k8s objects

### ISSUE THREAD

**Issue by aviweit** [accanto-systems/kubernetes-driver#6]
I get the below error (reported in the Execution UI page) when trying to instantiate an assembly

`No lifecycleType mapping for transition Install infrastructure type Kubernetes`

I on-boarded the driver with the below command parameters:

```
lmctl lifecycledriver add --type Kubernetes --url http://kubedriver:8294 dev
```
I can access driver's swagger UI via its NodePort.

I attache below my resource files

Definition/lm/resource.yaml
```
description: descriptor for k8s1
lifecycle:
  Install:
    drivers:
      Kubernetes:
        infrastructure_type:
          - '*'
default-driver:
  Kubernetes:
    infrastructure_type:
      - '*'
```
Lifecycle/Kubernetes/kegd.yaml
```
cleanupOn: Uninstall
compose:
  - name: Install
    deploy:
      - objects:
          file: obj.yaml
```
Lifecycle/Kubernetes/objects/obj.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-a
data:
  dataA: valueA
  dataB: valueB
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-b
data:
  dataA: valueA
  dataB: valueB
  dataC: valueC
```

Thanks.
